services:
  algorithm-exercises-ts-test:
    image: algorithm-exercises-ts:latest
    build:
      context: .
      target: testing
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
      BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./coverage:/app/coverage
    profiles: ["testing"]

  algorithm-exercises-ts-lint:
    image: algorithm-exercises-ts:lint
    build:
      context: .
      target: lint
    # environment:
      # LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
      # BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./:/app
    profiles: ["lint"]

  algorithm-exercises-ts-dev:
    image: algorithm-exercises-ts:dev
    build:
      context: .
      target: development
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
      BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./:/app
    profiles: ["development"]

  algorithm-exercises-ts:
    image: algorithm-exercises-ts:latest
    build:
      context: .
      target: production
    # volumes:
    #   - ./:/app
    profiles: ["production"]

## REFERENCES:
## (1) Passing Environment variable with fallback value:
##    https://stackoverflow.com/a/70772707/6366150
##
